### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by ghost** [pizzaoverhead/Chatterer#3]
Yeah, Visual Studio makes it easy with the .sln files, but there are things we need to know  anyway:
### Compilation:
- KSP SDK required?
- Unity required?
- CMake / MSMake required?
- Which versions of the above?
- Which version of Visual Studio to maintain .sln compatibility? (2010? 2012? Express yay/nay?)
### Contribution:
- How many changes per pull request?
- What coding style to follow?
- Are tests required, or optional?
- How are changes reviewed?

**Comment by Athlonic** [comment]
Hi,

As far as I am concerned :

Compilation:

KSP SDK required?
- nope

Unity required?
- nope

CMake / MSMake required?
- nope, what's this anyway ? ^^

Which versions of the above?
- Null.

Which version of Visual Studio to maintain .sln compatibility? (2010? 2012? Express yay/nay?)
- Latest VS Express. (just be sure to target NET3.5)

Contribution:

How many changes per pull request?
- let us make it simple : as much as you want/need.

What coding style to follow?
- as you wish, it may be a good idea to insert as much comments as possible though

Are tests required, or optional?
- yep, ensure it works as expected and that is doesn't burn cpus or crush HDD ^^

How are changes reviewed?
- Don't know yet, just put a complete changelog in readme file for now.

Best regards.

Edit: This github text format thingy is really getting on my nerves, seriously ><
